# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssigmaapi/type/market.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ssigmaapi/type/market.proto',
  package='ssigmaapi.type',
  syntax='proto3',
  serialized_options=_b('Z0github.com/kaito2/ssigmaapigo/type/market;market'),
  serialized_pb=_b('\n\x1bssigmaapi/type/market.proto\x12\x0essigmaapi.type\"*\n\x06Market\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08\x65xchange\x18\x02 \x01(\tB2Z0github.com/kaito2/ssigmaapigo/type/market;marketb\x06proto3')
)




_MARKET = _descriptor.Descriptor(
  name='Market',
  full_name='ssigmaapi.type.Market',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='ssigmaapi.type.Market.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='ssigmaapi.type.Market.exchange', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['Market'] = _MARKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Market = _reflection.GeneratedProtocolMessageType('Market', (_message.Message,), dict(
  DESCRIPTOR = _MARKET,
  __module__ = 'ssigmaapi.type.market_pb2'
  # @@protoc_insertion_point(class_scope:ssigmaapi.type.Market)
  ))
_sym_db.RegisterMessage(Market)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
