# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssigmaapi/flnd/v1/vitess.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ssigmaapi/flnd/v1/vitess.proto',
  package='ssigmaapi.vitess.v1',
  syntax='proto3',
  serialized_options=_b('Z.github.com/kaito2/ssigmaapigo/vitess/v1;vitess'),
  serialized_pb=_b('\n\x1essigmaapi/flnd/v1/vitess.proto\x12\x13ssigmaapi.vitess.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n\rVitessMessage\x12\x0c\n\x04text\x18\x01 \x01(\t2\xca\x02\n\x0fVitessServiceV1\x12J\n\nGetMessage\x12\x16.google.protobuf.Empty\x1a\".ssigmaapi.vitess.v1.VitessMessage\"\x00\x12M\n\rCreateMessage\x12\".ssigmaapi.vitess.v1.VitessMessage\x1a\x16.google.protobuf.Empty\"\x00\x12M\n\rUpdateMessage\x12\".ssigmaapi.vitess.v1.VitessMessage\x1a\x16.google.protobuf.Empty\"\x00\x12M\n\rDeleteMessage\x12\".ssigmaapi.vitess.v1.VitessMessage\x1a\x16.google.protobuf.Empty\"\x00\x42\x30Z.github.com/kaito2/ssigmaapigo/vitess/v1;vitessb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_VITESSMESSAGE = _descriptor.Descriptor(
  name='VitessMessage',
  full_name='ssigmaapi.vitess.v1.VitessMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='ssigmaapi.vitess.v1.VitessMessage.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['VitessMessage'] = _VITESSMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VitessMessage = _reflection.GeneratedProtocolMessageType('VitessMessage', (_message.Message,), dict(
  DESCRIPTOR = _VITESSMESSAGE,
  __module__ = 'ssigmaapi.flnd.v1.vitess_pb2'
  # @@protoc_insertion_point(class_scope:ssigmaapi.vitess.v1.VitessMessage)
  ))
_sym_db.RegisterMessage(VitessMessage)


DESCRIPTOR._options = None

_VITESSSERVICEV1 = _descriptor.ServiceDescriptor(
  name='VitessServiceV1',
  full_name='ssigmaapi.vitess.v1.VitessServiceV1',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=116,
  serialized_end=446,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMessage',
    full_name='ssigmaapi.vitess.v1.VitessServiceV1.GetMessage',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_VITESSMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateMessage',
    full_name='ssigmaapi.vitess.v1.VitessServiceV1.CreateMessage',
    index=1,
    containing_service=None,
    input_type=_VITESSMESSAGE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateMessage',
    full_name='ssigmaapi.vitess.v1.VitessServiceV1.UpdateMessage',
    index=2,
    containing_service=None,
    input_type=_VITESSMESSAGE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteMessage',
    full_name='ssigmaapi.vitess.v1.VitessServiceV1.DeleteMessage',
    index=3,
    containing_service=None,
    input_type=_VITESSMESSAGE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VITESSSERVICEV1)

DESCRIPTOR.services_by_name['VitessServiceV1'] = _VITESSSERVICEV1

# @@protoc_insertion_point(module_scope)
