# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from ssigmaapi.flnd.v1 import vitess_pb2 as ssigmaapi_dot_flnd_dot_v1_dot_vitess__pb2


class VitessServiceV1Stub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetMessage = channel.unary_unary(
        '/ssigmaapi.vitess.v1.VitessServiceV1/GetMessage',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=ssigmaapi_dot_flnd_dot_v1_dot_vitess__pb2.VitessMessage.FromString,
        )
    self.CreateMessage = channel.unary_unary(
        '/ssigmaapi.vitess.v1.VitessServiceV1/CreateMessage',
        request_serializer=ssigmaapi_dot_flnd_dot_v1_dot_vitess__pb2.VitessMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.UpdateMessage = channel.unary_unary(
        '/ssigmaapi.vitess.v1.VitessServiceV1/UpdateMessage',
        request_serializer=ssigmaapi_dot_flnd_dot_v1_dot_vitess__pb2.VitessMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.DeleteMessage = channel.unary_unary(
        '/ssigmaapi.vitess.v1.VitessServiceV1/DeleteMessage',
        request_serializer=ssigmaapi_dot_flnd_dot_v1_dot_vitess__pb2.VitessMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class VitessServiceV1Servicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VitessServiceV1Servicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetMessage': grpc.unary_unary_rpc_method_handler(
          servicer.GetMessage,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=ssigmaapi_dot_flnd_dot_v1_dot_vitess__pb2.VitessMessage.SerializeToString,
      ),
      'CreateMessage': grpc.unary_unary_rpc_method_handler(
          servicer.CreateMessage,
          request_deserializer=ssigmaapi_dot_flnd_dot_v1_dot_vitess__pb2.VitessMessage.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'UpdateMessage': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateMessage,
          request_deserializer=ssigmaapi_dot_flnd_dot_v1_dot_vitess__pb2.VitessMessage.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'DeleteMessage': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteMessage,
          request_deserializer=ssigmaapi_dot_flnd_dot_v1_dot_vitess__pb2.VitessMessage.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ssigmaapi.vitess.v1.VitessServiceV1', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
